### ISSUE TITLE
Feature request: link to post and/or post author's profile

### ISSUE THREAD

**Issue by ghost** [kennytilton/whoshiring#6]
Please provide a link to the job post on HN. Several submissions contain "email to the address in my profile" or similar wording. For those submissions, I have to find the post by paging through the entire thread. Even for posts that contain an email address, I prefer to try to find the author's name.

**Comment by kennytilton** [comment]
My apologies, @csprl-nowigence . I am missing these notifications for some reason.

You can jump to the original listing on HN by double-clicking the text body of the listing. This and other tips are listed under "Pro Tips", an inconspicuous button on the top-right.
