### ISSUE TITLE
Remove Triplebyte because they are shutting down

### ISSUE THREAD

**Issue by spolisar** [kennytilton/whoshiring#8]
You might want to remove the Triplebyte entry that always appears from the list. They've announced that they're being acquired by Karat and shutting down Triplebyte as a service in this [blog post](https://triplebyte.com/blog/karat-acquires-leading-adaptive-assessment-technology-from-triplebyte). Maybe Karat will roll out something like Triplebyte with their brand on it eventually, but based on the blog post, that won't be before Triplebyte shuts down.

**Comment by kennytilton** [comment]
Thanks! I missed a notification on this.

**Comment by kennytilton** [comment]
Thx again, @spolisar , should be gone now.
